package com.merge.merge.practice.model;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.UUID;

/**
 * A single Drill attempt for a given student on a given concept.
 *
 * <p>The {@code answer} field is stored server-side and never returned to the client.
 * All serialisation paths (DrillResponse) must omit it explicitly.</p>
 *
 * <p>The {@code idempotencyKey} is client-supplied on submission and prevents
 * duplicate-submit processing when the same request arrives more than once (network
 * retries). A compound unique index on (idempotencyKey) with sparse=true covers this.</p>
 *
 * <p>Anti-cheat evidence ({@code pasteAttempted}, {@code tabFocusLost}) is recorded
 * regardless of outcome. These fields are evidence only — they never block a submission
 * or alter the pass/fail decision. Their presence in the permanent record allows a
 * future honour-code review workflow without baking policy into the current codebase.</p>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Document(collection = "drills")
public class Drill {

    @Id
    private UUID id;

    /** The concept this Drill tests. */
    @Indexed
    private UUID conceptId;

    /** The student who requested this Drill. */
    @Indexed
    private UUID studentId;

    /**
     * The question text generated by Gemini via InstructorService.generateDrillSync.
     * Returned to the client.
     */
    private String question;

    /**
     * The expected answer. NEVER returned in any response DTO.
     * Comparison on submit: trimmed + case-insensitive (see DrillService).
     */
    private String answer;

    /** True once the student has submitted and the answer matched. */
    private boolean passed;

    /** XP credited on a pass. 0 until the Drill is resolved. */
    private int xpAwarded;

    /** Feedback generated by InstructorService.generateComprehensionSync on pass. */
    private String feedback;

    /** Current lifecycle state of this Drill. PENDING until submitted or deadline expires. */
    private SubmissionStatus status;

    /**
     * Hard deadline for submission. Set at creation to Instant.now() plus 10 seconds.
     * A submission arriving after this instant is treated as an automatic fail,
     * regardless of whether the answer is correct.
     */
    private Instant serverDeadline;

    /** Instant the student actually submitted. Null until submission occurs. */
    private Instant answeredAt;

    /**
     * Client-supplied key for idempotent submission. The submit endpoint ignores
     * a second request that carries the same key and returns the already-resolved Drill.
     * Sparse unique index prevents duplicates without requiring all Drills to carry a key.
     */
    @Indexed(unique = true, sparse = true)
    private String idempotencyKey;

    /**
     * True if the client reported that the student pasted text into the answer field.
     * Evidence only — recorded on all outcomes, never causes a submission to be blocked.
     */
    private boolean pasteAttempted;

    /**
     * Count of tab-focus-lost events reported by the client during this Drill.
     * Evidence only — recorded on all outcomes, never causes a submission to be blocked.
     */
    private int tabFocusLost;

    /** Instant this Drill was created. */
    private Instant createdAt;
}
